title = "Francisco Souza"
base_url = "https://blog.fsouza.dev"

compile_sass = false

default_language = "en"
build_search_index = true

generate_feed = true
feed_filename = "atom.xml"

theme = "hyde"

[markdown]
highlight_code = true
highlight_theme = "ir-white"
external_links_target_blank = true

[extra]
author = "Francisco Souza"
hyde_reverse = true
hyde_links = [
    {url = "https://github.com/fsouza", name = "GitHub"},
    {url = "https://linkedin.com/in/franciscosouza", name = "LinkedIn"},
    {url = "https://twitter.com/franciscosouza", name = "Twitter"},
]
