on:
  push:
    branches:
      - main

name: Build and deploy GH Pages
jobs:
  build:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: download zola
        run: |
          curl -sLo /tmp/zola.tar.gz https://github.com/getzola/zola/releases/download/v0.15.3/zola-v0.15.3-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf /tmp/zola.tar.gz

      - name: build
        run: ./zola build

      - name: write cname
        run: |
          echo blog.fsouza.dev > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
