on:
  push:
    branches:
      - main

permissions:
  contents: write

name: Build and deploy GH Pages
jobs:
  build:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0

      - name: download zola
        run: |
          curl -sLo /tmp/zola.tar.gz https://github.com/getzola/zola/releases/download/v0.16.1/zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf /tmp/zola.tar.gz

      - name: build
        run: ./zola build

      - name: write cname
        run: |
          echo blog.fsouza.dev > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
